### ISSUE TITLE
MAWPS dataset

### ISSUE THREAD

**Issue by gychant** [2003pro/Graph2Tree#4]
Hi Jipeng,

Where can we find the MAWPS dataset used for the evaluation? What is the original download link?

Thanks!

**Comment by KnightZhang625** [comment]
Check the original MAWPS paper, please. https://aclanthology.org/N16-1136/

**Comment by 2003pro** [comment]
Thanks for the response @KnightZhang625. For @gychant , I have put the closet version to original MAWPS here https://github.com/2003pro/Graph2Tree/blob/master/mawps/data/mawps_mathdqn_data_1016_unrate.json .
